x-tox-env: &x-tox-env >
  TOX_CMD="tox --skip-missing-interpreters=false -v"

x-tox-install: &x-tox-install |
  pip install -U pip
  pip install 'tox<=3.14.5' 'virtualenv<20.0.5'

x-linux-shard: &x-linux-shard
  os: linux
  dist: bionic
  language: python
  install: *x-tox-install
  env: *x-tox-env
  addons:
    apt:
      packages:
        - python3-venv
  cache:
    # The default is 3 minutes (180).
    timeout: 300
    directories:
      - .pyenv_test

# Pre-built Python distributions available on bionic (Ubuntu 18.04) are listed here:
#   https://docs.travis-ci.com/user/languages/python/

x-linux-27-shard: &x-linux-27-shard
  <<: *x-linux-shard
  python: 2.7.18

x-linux-pypy-shard: &x-linux-pypy-shard
  <<: *x-linux-shard
  python: pypy2.7-7.2.0

x-linux-38-shard: &x-linux-38-shard
  <<: *x-linux-shard
  python: 3.8.2

x-pyenv-env: &x-pyenv-env >
  PYENV_ROOT=~/.pyenv-pex
  PATH="${PYENV_ROOT}/shims:${PATH}"

x-pyenv-install: &x-pyenv-install |
  # Ensure we have the targeted Python for tox to find on $PATH
  PYENV="${PYENV_ROOT}/bin/pyenv"
  if [ ! -x "${PYENV}" ]; then
    rm -rf ${PYENV_ROOT}
    git clone https://github.com/pyenv/pyenv "${PYENV_ROOT}";
  fi
  GIT_DIR="${PYENV_ROOT}/.git" git pull --ff-only
  "${PYENV}" install --keep --skip-existing ${PYENV_VERSION}
  "${PYENV}" global ${PYENV_VERSION}

x-pyenv-39-env: &x-pyenv-39-env >
  PYENV_VERSION=3.9.1

x-linux-3-shard: &x-linux-39-shard
  <<: *x-linux-shard
  env:
    - *x-tox-env
    - *x-pyenv-env
    - *x-pyenv-39-env
  cache:
    # The default is 3 minutes (180).
    timeout: 300
    directories:
      - .pyenv_test
      - "${PYENV_ROOT}"
  install:
    - *x-tox-install
    - *x-pyenv-install

x-osx-shard: &x-osx-shard
  os: osx
  osx_image: xcode9.4
  language: generic
  cache:
    # The default is 3 minutes (180).
    timeout: 300
    directories:
      - .pyenv_test
      - "${PYENV_ROOT}"
  install:
    - *x-tox-install
    - *x-pyenv-install

x-osx-27-shard: &x-osx-27-shard
  <<: *x-osx-shard
  env:
    - *x-tox-env
    - *x-pyenv-env
    - PYENV_VERSION=2.7.18

x-osx-39-shard: &x-osx-39-shard
  <<: *x-osx-shard
  env:
    - *x-tox-env
    - *x-pyenv-env
    - *x-pyenv-39-env

# NB: Travis partitions caches using a combination of os, language amd env vars. As such, we do not
# use TOXENV and instead pass the toxenv via -e on the command line. This helps ensure we share
# caches as much as possible (eg: all linux python 2.7.15 shards share a cache).
matrix:
  include:
    - <<: *x-linux-shard
      name: TOXENV=format-check
      script: ${TOX_CMD} -e format-check

    - <<: *x-linux-shard
      name: TOXENV=typecheck
      script: ${TOX_CMD} -e typecheck

    - <<: *x-linux-38-shard
      name: TOXENV=vendor-check
      script: ${TOX_CMD} -e vendor-check

    - <<: *x-linux-27-shard
      name: TOXENV=py27
      script: ${TOX_CMD} -e py27

    - <<: *x-linux-27-shard
      name: TOXENV=py27-subprocess
      script: ${TOX_CMD} -e py27-subprocess

    - <<: *x-linux-shard
      name: TOXENV=py35
      python: 3.5.9
      script: ${TOX_CMD} -e py35

    - <<: *x-linux-shard
      name: TOXENV=py36
      python: 3.6.10
      script: ${TOX_CMD} -e py36

    - <<: *x-linux-shard
      name: TOXENV=py37
      python: 3.7.7
      script: ${TOX_CMD} -e py37

    - <<: *x-linux-38-shard
      name: TOXENV=py38
      script: ${TOX_CMD} -e py38

    - <<: *x-linux-39-shard
      name: TOXENV=py39
      script: ${TOX_CMD} -e py39

    - <<: *x-linux-pypy-shard
      name: TOXENV=pypy
      script: ${TOX_CMD} -e pypy

    - <<: *x-linux-27-shard
      name: TOXENV=py27-integration
      script: ${TOX_CMD} -e py27-integration

    - <<: *x-linux-39-shard
      name: TOXENV=py39-integration
      script: ${TOX_CMD} -e py39-integration

    - <<: *x-linux-pypy-shard
      name: TOXENV=pypy-integration
      script: ${TOX_CMD} -e pypy-integration

    - <<: *x-osx-27-shard
      name: TOXENV=py27
      script: ${TOX_CMD} -e py27

    - <<: *x-osx-39-shard
      name: TOXENV=py39
      script: ${TOX_CMD} -e py39

    - <<: *x-osx-27-shard
      name: TOXENV=py27-integration
      script: ${TOX_CMD} -e py27-integration

    - <<: *x-osx-39-shard
      name: TOXENV=py39-integration
      script: ${TOX_CMD} -e py39-integration
