# Enables support for a docker container-based build
# which should provide faster startup times and beefier
# "machines".
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
dist: trusty

cache:
  directories:
    - .pyenv_test

language: python

matrix:
  include:
    - os: osx
      python: "2.7"
      env: TOXENV=py27

    - os: osx
      python: "3.6"
      env: TOXENV=py36

    - os: osx
      python: "2.7"
      env: TOXENV=py27-integration

    - os: osx
      python: "3.6"
      env: TOXENV=py36-integration

    - python: "2.7"
      env: TOXENV=style

    - python: "2.7"
      env: TOXENV=isort-check

    - python: "2.7"
      env: TOXENV=py27

    - python: "2.7"
      env: TOXENV=py27-subprocess

    - python: "2.7"
      env: TOXENV=py27-requests

    - python: "2.7"
      env: TOXENV=py27-requests-cachecontrol

    - python: "3.4"
      env: TOXENV=py34

    - python: "3.5"
      env: TOXENV=py35

    - python: "3.6"
      env: TOXENV=py36

    - python: "3.6"
      env: TOXENV=py36-requests

    - python: "3.6"
      env: TOXENV=py36-requests-cachecontrol

    - python: "pypy"
      env: TOXENV=pypy

    - python: "2.7"
      env: TOXENV=py27-integration

    - python: "3.6"
      env: TOXENV=py36-integration

    - python: "pypy"
      env: TOXENV=pypy-integration

install:
  - pip install -U tox "setuptools>=36"

script:
  - ./scripts/ci.sh
